version: '3'
services:
  adminer:
    image: adminer
    ports:
      - '8080:8080'
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: alkoselain-dev
      POSTGRES_PASSWORD: password
